import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgPath = path.resolve(__dirname, "..", "package.json");
const outPath = path.resolve(__dirname, "..", "src", "generated-version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const content =
  "// Auto-generated by scripts/sync-version.mjs from package.json — do not edit.\n" +
  `export const PLUGIN_VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(outPath, content);
console.log(`sync-version: wrote ${pkg.version} to ${path.relative(process.cwd(), outPath)}`);
